# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9768256ca22b05d8fb76d8aca34c28fb1a7207e9b4edd912cdc494627c105b36166972007119e41dba94f4530de930fca9cc983271b159ed1d093dabbf8fe6fd

test:
  secret_key_base: 6e96078f3a3e8580fdf6a1ee597fa6fc35f64f4929a4029067419cb499cd42b28e5a09443da5143e50bffade032766111c1d6d87dd5325599fe12aec3e82a919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
